"""
CLI entry point for running a single scenario.

    uv run python -m gym_runtime.run <scenario_id> [--harness ...] [--model ...] [--out ...]

Examples:

    # Smoke test without an LLM — verifies plumbing and produces a null baseline
    uv run python -m gym_runtime.run hr_s1_termination_reorg --harness dummy

    # Real agent run with Claude
    uv run python -m gym_runtime.run hr_s1_termination_reorg \\
        --harness anthropic --model claude-sonnet-4-5 \\
        --out trajectories/

    # List all available scenarios
    uv run python -m gym_runtime.run --list
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

from gym_runtime.scenario import Scenario, ScenarioIndex
from gym_runtime.session import Session, SessionConfig
from gym_runtime.harness.dummy import DummyHarness


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="gym_runtime.run",
        description="Run a single scenario through an agent harness and score it.",
    )
    parser.add_argument("scenario_id", nargs="?", help="e.g. hr_s1_termination_reorg")
    parser.add_argument("--list", action="store_true", help="List all scenarios and exit")
    parser.add_argument(
        "--harness",
        choices=["dummy", "anthropic", "openai"],
        default="dummy",
        help="Which agent harness to use (default: dummy, no LLM)",
    )
    parser.add_argument("--model", default="claude-sonnet-4-5", help="Model id for the harness")
    parser.add_argument(
        "--reasoning-effort",
        default=None,
        help="OpenAI reasoning effort: minimal|low|medium|high (or a custom value "
             "your account accepts). Only used by the openai harness.",
    )
    parser.add_argument("--max-turns", type=int, default=80)
    parser.add_argument("--max-wall-seconds", type=float, default=1200.0)
    parser.add_argument("--out", default="trajectories", help="Directory for trajectory JSON output")
    parser.add_argument(
        "--run-label",
        default=None,
        help="Optional label appended to the trajectory filename to prevent collisions "
             "when running the same (scenario, model) pair multiple times.",
    )
    parser.add_argument(
        "--npc-llm",
        action="store_true",
        help="Enable LLM-as-NPC: NPC replies are generated by an OpenAI model in character "
             "from each persona's YAML record, instead of a deterministic stub. Required for "
             "the agent's discovery protocol to work (asking NPCs about their preferences).",
    )
    parser.add_argument(
        "--npc-model",
        default="gpt-5.4",
        help="Model used for LLM-as-NPC replies (default: gpt-5.4 at low reasoning effort).",
    )
    parser.add_argument(
        "--quiet", action="store_true", help="Print only the final summary JSON",
    )
    args = parser.parse_args(argv)

    if args.list:
        scenarios = ScenarioIndex.list_all()
        print(f"{len(scenarios)} scenarios:")
        by_domain: dict[str, list[str]] = {}
        for sid, dom in scenarios:
            by_domain.setdefault(dom, []).append(sid)
        for dom in sorted(by_domain):
            print(f"\n  {dom}/")
            for sid in sorted(by_domain[dom]):
                print(f"    {sid}")
        return 0

    if not args.scenario_id:
        parser.error("scenario_id is required (or pass --list)")

    if not args.quiet:
        print(f"Loading scenario {args.scenario_id}...", file=sys.stderr)

    try:
        scenario = Scenario.load(args.scenario_id)
    except Exception as exc:
        print(f"Failed to load scenario: {exc}", file=sys.stderr)
        return 2

    if not args.quiet:
        print(
            f"  domain={scenario.domain}  "
            f"personas={len(scenario.personas.ids())}  "
            f"inputs={len(scenario.input_files)}  "
            f"verifier={scenario.verifier_cls.__name__}  "
            f"tasks={len(scenario.verifier_cls.task_verifiers)}",
            file=sys.stderr,
        )

    # Build harness
    if args.harness == "dummy":
        harness = DummyHarness()
    elif args.harness == "anthropic":
        from gym_runtime.harness.anthropic import AnthropicHarness
        harness = AnthropicHarness(model=args.model)
    elif args.harness == "openai":
        from gym_runtime.harness.openai import OpenAIHarness
        harness = OpenAIHarness(
            model=args.model,
            reasoning_effort=args.reasoning_effort or "high",
        )
    else:
        parser.error(f"unknown harness: {args.harness}")
        return 2

    config = SessionConfig(
        max_turns=args.max_turns,
        max_wall_seconds=args.max_wall_seconds,
    )

    npc_llm_client = None
    if args.npc_llm:
        from gym_runtime.npc import OpenAINPCClient
        npc_llm_client = OpenAINPCClient(model=args.npc_model, reasoning_effort="low")
        if not args.quiet:
            print(f"  npc_llm=enabled ({args.npc_model})", file=sys.stderr)

    if not args.quiet:
        print(f"Running session ({args.harness}:{harness.model})...", file=sys.stderr)

    session = Session(scenario, harness, config, npc_llm_client=npc_llm_client)
    result = session.run()

    # Save trajectory
    out_dir = Path(args.out)
    out_dir.mkdir(parents=True, exist_ok=True)
    suffix = f"__{args.run_label}" if args.run_label else ""
    traj_path = out_dir / f"{args.scenario_id}__{harness.model.replace('/', '_')}{suffix}.json"
    result.save_trajectory(str(traj_path))

    # Also save the action log as JSONL for verifier-layer consumers
    jsonl_path = out_dir / f"{args.scenario_id}__{harness.model.replace('/', '_')}{suffix}.jsonl"
    from gym_runtime.recorder import ActionRecorder
    rec = ActionRecorder(actions=result.action_log)
    rec.save(str(jsonl_path))

    # Print summary
    summary = result.summary()
    print(json.dumps(summary, indent=2, default=str))
    if not args.quiet:
        print(f"\nTrajectory: {traj_path}", file=sys.stderr)
        print(f"Action log: {jsonl_path}", file=sys.stderr)

    # Exit nonzero if the verifier reports a hard failure
    if result.verifier_report is not None and not result.verifier_report.passed:
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
